<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['samba_administrator_account'] = 'Учётная запись администратора';
$lang['samba_app_description'] = 'Windows Networking (Samba) provides the necessary glue to interoperate with Windows systems.  The app provides authentication services, file and print, along with Windows domain management.';
$lang['samba_app_name'] = 'Windows Networking (Samba)';
$lang['samba_computers'] = 'Компьютер';
$lang['samba_driver_has_not_been_initialized'] = 'Драйвер не был инициализирован';
$lang['samba_file_share_tooltip'] = 'If you would like to create network file shares, please use the Flexshare app.';
$lang['samba_initializing_core_system'] = 'Инициализация ядра системы, пожалуйста, будьте терпеливы.';
$lang['samba_initializing_warning'] = 'Инициализация может занять минуту или две, пожалуйста, будьте терпеливы';
$lang['samba_master_node_needs_initialization'] = 'Главный узел должен быть инициализирован перед продолжением.';
$lang['samba_mode'] = 'Режим';
$lang['samba_samba_directory_installed_warning'] = 'Программное обеспечение Samba Каталог установлено, таким образом, вам больше не нужно это приложение';
