#!/bin/sh

if [ -e /var/clearos/samba/lock/initializing ]; then
    if [ -e /var/clearos/samba/initialized ]; then
        rm -f /var/clearos/samba/lock/initializing
    else
        logger -p local6.notice -t samba "skipping event, initialization in progress"
        exit 0
    fi
fi

if [ -e /var/clearos/samba/lock/initializing_local ]; then
    if [ -e /var/clearos/samba/initialized_local ]; then
        rm -f /var/clearos/samba/lock/initializing_local
    else
        logger -p local6.notice -t samba "skipping event, local initialization in progress"
        exit 0
    fi
fi


set -e

if ( [ -e /var/clearos/openldap_directory/ready_for_extensions ] || [ -e /var/clearos/accounts/initialized ] ); then
    READY="yes"
fi

if ( [ ! -e /var/clearos/samba/initialized_openldap ] && [ -n "$READY" ] ); then
    logger -p local6.notice -t samba "checking Samba directory initialization"
    ( flock -x -n 200
        logger -p local6.notice -t samba "initializing Samba directory"
        [ -x /usr/sbin/app-samba-openldap-initialize ] && /usr/sbin/app-samba-openldap-initialize >/dev/null 2>&1
    ) 200>/var/tmp/samba-init
fi

# TODO: overkill - needs to be successful once
if [ -e /var/clearos/samba_common/initialized ]; then
    [ -x /usr/sbin/add-windows-group-info ] && /usr/sbin/add-windows-group-info >/dev/null 2>&1
    [ -x /usr/sbin/password-policies-synchronize ] && /usr/sbin/password-policies-synchronize >/dev/null 2>&1
fi
