<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['samba_administrator_account'] = 'Administrator Account';
$lang['samba_app_description'] = 'Windows Networking provides the necessary glue to interoperate with Windows systems.  The app provides authentication services, file and print, along with Windows domain management.';
$lang['samba_app_name'] = 'Windows Networking';
$lang['samba_computers'] = 'Computers';
$lang['samba_driver_has_not_been_initialized'] = 'Driver has not been initialized.';
$lang['samba_file_share_tooltip'] = 'If you would like to create network file shares, please use the Flexshare app.';
$lang['samba_initializing_core_system'] = 'Initializing core system, please be patient.';
$lang['samba_initializing_warning'] = 'Initialization may take a minute or two, please be patient.';
$lang['samba_master_node_needs_initialization'] = 'Master node needs to be initialized before proceeding.';
$lang['samba_mode'] = 'Mode';
$lang['samba_samba_directory_installed_warning'] = 'The Samba Directory software is installed, so you no longer need this app.';
