<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['samba_administrator_account'] = 'Konto administratora';
$lang['samba_app_description'] = 'Windows Networking (Samba) provides the necessary glue to interoperate with Windows systems.  The app provides authentication services, file and print, along with Windows domain management.';
$lang['samba_app_name'] = 'Windows Networking (Samba)';
$lang['samba_computers'] = 'Komputery';
$lang['samba_driver_has_not_been_initialized'] = 'Sterownik nie został zainicjowany.';
$lang['samba_file_share_tooltip'] = 'Jeżeli chciałbyś utworzyć udziały sieciowe, proszę skorzystać z aplikacji Flexshare.';
$lang['samba_initializing_core_system'] = 'Inicjuję rdzeń systemu, prosimy o cierpliwość.';
$lang['samba_initializing_warning'] = 'Inicjacja może zająć minutę lub dwie, prosimy o cierpliwość.';
$lang['samba_master_node_needs_initialization'] = 'Węzeł nadrzędny powinien zostać zainicjowany przed kontynuacją.';
$lang['samba_mode'] = 'Tryb';
$lang['samba_samba_directory_installed_warning'] = 'Oprogramowanie usług katalogowych Samba jest zainstalowane, więc już nie potrzebujesz tej aplikacji.';
